<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        $products = [
            [
                'name' => 'Paracetamol 500mg',
                'description' => 'Alivia el dolor y reduce la fiebre.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 2.99,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 100,
            ],
            [
                'name' => 'Ibuprofeno 400mg',
                'description' => 'Antiinflamatorio y analgésico.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 4.50,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 80,
            ],
            [
                'name' => 'Amoxicilina 500mg',
                'description' => 'Antibiótico de amplio espectro.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 12.99,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 50,
            ],
            [
                'name' => 'Vitamina C 1000mg',
                'description' => 'Suplemento dietético para el sistema inmune.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 8.99,
                'category_id' => Category::where('name', 'Vitaminas')->first()->id,
                'stock' => 50,
            ],
            [
                'name' => 'Multivitamínico',
                'description' => 'Complejo vitamínico para la salud general.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 15.99,
                'category_id' => Category::where('name', 'Vitaminas')->first()->id,
                'stock' => 40,
            ],
            [
                'name' => 'Omega 3 1000mg',
                'description' => 'Suplemento dietético para la salud cardiovascular.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 12.99,
                'category_id' => Category::where('name', 'Suplementos')->first()->id,
                'stock' => 75,
            ],
            [
                'name' => 'Proteína Whey',
                'description' => 'Suplemento proteico para el crecimiento muscular.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 29.99,
                'category_id' => Category::where('name', 'Suplementos')->first()->id,
                'stock' => 25,
            ],
            [
                'name' => 'Ginseng',
                'description' => 'Suplemento para aumentar la energía y reducir el estrés.',
                'price' => 19.99,
                'category_id' => Category::where('name', 'Suplementos')->first()->id,
                'stock' => 60,
            ],
            [
                'name' => 'Alcohol en Gel 70%',
                'description' => 'Desinfectante de manos.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 3.50,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 200,
            ],
            [
                'name' => 'Jabón Antibacterial',
                'description' => 'Jabón de manos con propiedades antibacterianas.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 2.99,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 150,
            ],
            [
                'name' => 'Crema Hidratante',
                'description' => 'Crema para mantener la piel hidratada.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 7.99,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 60,
            ],
            [
                'name' => 'Protector Solar SPF 50',
                'description' => 'Protección solar de amplio espectro.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 10.99,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 40,
            ],
            [
                'name' => 'Termómetro Digital',
                'description' => 'Termómetro de alta precisión para medir la temperatura corporal.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 15.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 30,
            ],
            [
                'name' => 'Oxímetro de Pulso',
                'description' => 'Dispositivo para medir la saturación de oxígeno en la sangre.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 25.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 20,
            ],
            [
                'name' => 'Tensiómetro Digital',
                'description' => 'Dispositivo para medir la presión arterial.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 45.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 15,
            ],
            [
                'name' => 'Bastón Ortopédico',
                'description' => 'Bastón ajustable para soporte y equilibrio.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 19.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 10,
            ],
            [
                'name' => 'Silla de Ruedas',
                'description' => 'Silla de ruedas plegable para movilidad.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 199.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 5,
            ],
            [
                'name' => 'Mascarilla Quirúrgica',
                'description' => 'Mascarilla de protección para uso médico.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 0.50,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 500,
            ],
            [
                'name' => 'Gasa Estéril',
                'description' => 'Gasa para curaciones y heridas.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 1.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 200,
            ],
            [
                'name' => 'Venda Elástica',
                'description' => 'Venda para soporte y compresión.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 2.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 150,
            ],
            [
                'name' => 'Jarabe para la Tos',
                'description' => 'Jarabe expectorante para aliviar la tos.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 6.99,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 80,
            ],
            [
                'name' => 'Loratadina 10mg',
                'description' => 'Antihistamínico para alergias.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 3.99,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 120,
            ],
            [
                'name' => 'Aspirina 100mg',
                'description' => 'Antiinflamatorio y analgésico.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 4.99,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 90,
            ],
            [
                'name' => 'Suero Oral',
                'description' => 'Solución oral para la rehidratación.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 5.99,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 70,
            ],
            [
                'name' => 'Vendas Adhesivas',
                'description' => 'Vendas adhesivas para pequeñas heridas.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 2.50,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 100,
            ],
            [
                'name' => 'Enjuague Bucal',
                'description' => 'Enjuague bucal para una higiene completa.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 4.99,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 50,
            ],
            [
                'name' => 'Shampoo Anticaspa',
                'description' => 'Shampoo para el control de la caspa.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 6.99,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 40,
            ],
            [
                'name' => 'Gotas para los Ojos',
                'description' => 'Solución oftálmica para aliviar la irritación ocular.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 7.99,
                'category_id' => Category::where('name', 'Medicamentos')->first()->id,
                'stock' => 60,
            ],
            [
                'name' => 'Pañales para Adultos',
                'description' => 'Pañales desechables para adultos.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 14.99,
                'category_id' => Category::where('name', 'Equipos Médicos')->first()->id,
                'stock' => 30,
            ],
            [
                'name' => 'Tiritas Adhesivas',
                'description' => 'Tiritas para pequeñas cortaduras y raspones.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 1.50,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 200,
            ],
            [
                'name' => 'Crema Analgésica',
                'description' => 'Crema para el alivio del dolor muscular.',
                'long_description' => $faker->paragraph,
                'composition' => $faker->paragraph,
                'instructions' => $faker->paragraph,
                'warning' => $faker->paragraph,
                'price' => 5.99,
                'category_id' => Category::where('name', 'Cuidado Personal')->first()->id,
                'stock' => 80,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
